# Packages

In [1]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
import nltk
from nltk.tokenize import word_tokenize
from sklearn.metrics.pairwise import cosine_distances
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
import matplotlib.pyplot as plt
from sklearn.model_selection import cross_val_score
import numpy as np

# Content = Business's Description

In [2]:
df = pd.read_csv("data/sponsors.csv")
df

name          category  \
0                                       Asus Indonesia           Sponsor   
1                                           Hydro Coco           Sponsor   
2                                            Nutrijell           Sponsor   
3                                     Zalora Indonesia           Sponsor   
4                                               Marina           Sponsor   
..                                                 ...               ...   
857               photobooth wedding murah jabodetabek  Equipment Rental   
858                      photo booth ulang tahun murah  Equipment Rental   
859  MobileTrans - Wa Transfer dan Line Transfer Or...  Equipment Rental   
860    SEWA WIFI JEPANG | JAPAN WIFI | SEWA JAPAN WIFI  Equipment Rental   
861  drfone Whatsapp Transfer Original [KHUSUS MAC]...  Equipment Rental   

            sub-category                                              about  \
0    Technology Hardware  ASUS is passionate about technology and driven...   
1        Food & Beverage  Tentang Hydro Coco\r\nHydro Coco terbuat dari ...   
2        Food & Beverage  Nutrijell is a leading agar-agar brand in Indo...   
3             E-Commerce  Zalora Indonesia, the largest online fashion r...   
4      Personal & Beauty  Marina Natural is a leading Indonesian cosmeti...   
..                   ...                                                ...   
857           Photobooth               photobooth wedding murah jabodetabek   
858           Photobooth                      photo booth ulang tahun murah   
859           Photobooth  MobileTrans - Wa Transfer dan Line Transfer Or...   
860           Photobooth    SEWA WIFI JEPANG | JAPAN WIFI | SEWA JAPAN WIFI   
861           Photobooth  drfone Whatsapp Transfer Original [KHUSUS MAC]...   

                                              metadata  
0    Sponsor Technology Hardware ASUS is passionate...  
1    Sponsor Food & Beverage Tentang Hydro Coco\r\n...  
2    Sponsor Food & Beverage Nutrijell is a leading...  
3    Sponsor E-Commerce Zalora Indonesia, the large...  
4    Sponsor Personal & Beauty Marina Natural is a ...  
..                                                 ...  
857  Equipment Rental Photobooth photobooth wedding...  
858  Equipment Rental Photobooth photo booth ulang ...  
859  Equipment Rental Photobooth MobileTrans - Wa T...  
860  Equipment Rental Photobooth SEWA WIFI JEPANG |...  
861  Equipment Rental Photobooth drfone Whatsapp Tr...  

[862 rows x 5 columns]

# Encode All About to a Bank

In [3]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to C:\Users\Arsya
[nltk_data]     Amalia\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [4]:
bow = CountVectorizer(stop_words="english", min_df=1, tokenizer=word_tokenize)
bank = bow.fit_transform(df.metadata)

## Step 1: Encode What User Click

In [5]:
idx = 66

In [6]:
content = df.loc[idx, "metadata"]
content

'Sponsor Personal & Beauty Makeover is an Indonesian cosmetics brand offering a comprehensive range of makeup and skincare products. With a focus on providing high-quality and on-trend beauty items, Makeover has gained popularity among consumers seeking both traditional and modern beauty solutions.'

In [7]:
code = bow.transform([content])
code.toarray()

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

## Step 2: Document Search

In [8]:
dist = cosine_distances(code, bank)
dist

array([[0.75851277, 0.88859377, 0.70621517, 0.78445245, 0.68715064,
        0.69543382, 0.74952253, 0.79675608, 0.70670577, 0.73547997,
        0.70997345, 0.78054973, 0.7451983 , 0.71042975, 0.73489413,
        0.75828058, 0.76216464, 0.78841818, 0.76566679, 0.72397378,
        0.75241797, 0.74215602, 0.68813284, 0.76901369, 0.77016514,
        0.70610923, 0.7498918 , 0.57269639, 0.72998212, 0.8059039 ,
        0.83697217, 0.83295903, 0.77571935, 0.75483361, 0.77980999,
        0.67600313, 0.81229654, 0.75060813, 0.7628821 , 0.7475866 ,
        0.6448576 , 0.67463742, 0.66238815, 0.79566466, 0.73660671,
        0.73917973, 0.79826335, 0.78510261, 0.79903003, 0.73752467,
        0.81442313, 0.75914517, 0.73057466, 0.7606225 , 0.77169417,
        0.71067834, 0.42616442, 0.79380348, 0.7634779 , 0.76053963,
        0.42758022, 0.73959275, 0.63968168, 0.7432237 , 0.79193741,
        0.74316525, 0.        , 0.83354992, 0.80097892, 0.76671526,
        0.76194412, 0.65060117, 0.76671526, 0.61

In [9]:
rec_idx = dist.argsort()[0, 1:11]
rec_idx

array([56, 60, 80, 83, 27, 73, 62, 40, 71, 42], dtype=int64)

## Step 3: Recommend

In [10]:
df.loc[rec_idx]

name category           sub-category  \
56           Mustika Ratu  Sponsor      Personal & Beauty   
60          Holika-holika  Sponsor      Personal & Beauty   
80                 Wardah  Sponsor      Personal & Beauty   
83          The Body Shop  Sponsor      Personal & Beauty   
27                Paragon  Sponsor      Personal & Beauty   
73                  Nivea  Sponsor      Personal & Beauty   
62  Damn I Love Indonesia  Sponsor     Textiles & Apparel   
40       Head & Shoulders  Sponsor      Personal & Beauty   
71              Bukalapak  Sponsor             E-Commerce   
42               Alfamart  Sponsor  Distribution & Retail   

                                                about  \
56  Mustika Ratu is a well-known Indonesian cosmet...   
60  Holika-holika is a South Korean cosmetics bran...   
80  Wardah is an Indonesian cosmetics and skincare...   
83  The Body Shop is a global beauty and cosmetics...   
27  Paragon Technology and Innovation is an Indone...   
73  Nivea is a global brand that primarily focuses...   
62  Damn I Love Indonesia (DILo) is a lifestyle br...   
40  Head & Shoulders is a well-known brand of anti...   
71  Bukalapak is an Indonesian online marketplace ...   
42  Alfamart is a leading Indonesian convenience s...   

                                             metadata  
56  Sponsor Personal & Beauty Mustika Ratu is a we...  
60  Sponsor Personal & Beauty Holika-holika is a S...  
80  Sponsor Personal & Beauty Wardah is an Indones...  
83  Sponsor Personal & Beauty The Body Shop is a g...  
27  Sponsor Personal & Beauty Paragon Technology a...  
73  Sponsor Personal & Beauty Nivea is a global br...  
62  Sponsor Textiles & Apparel Damn I Love Indones...  
40  Sponsor Personal & Beauty Head & Shoulders is ...  
71  Sponsor E-Commerce Bukalapak is an Indonesian ...  
42  Sponsor Distribution & Retail Alfamart is a le...

# ML Engineering: Sum Them All Up

In [11]:
class RecommenderSystem:
    def __init__(self, data, content_col):
        self.df = pd.read_csv(data)
        self.content_col = content_col
        self.encoder = None
        self.model = None

    def preprocess_data(self):
        # Assuming 'metadata' contains the features and 'category' contains the labels
        X_train, X_val, y_train, y_val = train_test_split(
            self.df['metadata'], self.df['category'], test_size=0.2, random_state=42
        )
        return X_train, X_val, y_train, y_val

    def train_model(self, X_train, y_train, X_val, y_val):
        # Create a pipeline with CountVectorizer and MultinomialNB
        model = Pipeline([
            ('vectorizer', CountVectorizer(stop_words="english", tokenizer=word_tokenize)),
            ('classifier', MultinomialNB())
        ])

        # Train the model
        model.fit(X_train, y_train)

        # Evaluate accuracy on the validation set
        val_predictions = model.predict(X_val)
        accuracy = accuracy_score(y_val, val_predictions)
        print(f'Validation Accuracy: {accuracy}')

        return model

    def plot_accuracy(self, model, X_val, y_val):
        # Plot cross-validation accuracy
        cv_scores = cross_val_score(model, X_val, y_val, cv=5)
        print(f'Cross-validation Accuracy: {np.mean(cv_scores)}')

    def recommend(self, idx, topk=10):
        content = df.loc[idx, self.content_col]
        code = self.encoder.transform([content])
        dist = cosine_distances(code, self.bank)
        rec_idx = dist.argsort()[0, 1:(topk+1)]
        return self.df.loc[rec_idx]

    def run(self):
        X_train, X_val, y_train, y_val = self.preprocess_data()
        self.encoder = CountVectorizer(stop_words="english", tokenizer=word_tokenize)
        self.bank = self.encoder.fit_transform(self.df[self.content_col])
        self.model = self.train_model(X_train, y_train, X_val, y_val)
        self.plot_accuracy(self.model, X_val, y_val)

In [12]:
recsys = RecommenderSystem("data/sponsors.csv", content_col="metadata")

In [13]:
recsys.run()

Validation Accuracy: 1.0
Cross-validation Accuracy: 1.0


In [14]:
recsys.recommend(66)

name category           sub-category  \
56           Mustika Ratu  Sponsor      Personal & Beauty   
60          Holika-holika  Sponsor      Personal & Beauty   
80                 Wardah  Sponsor      Personal & Beauty   
83          The Body Shop  Sponsor      Personal & Beauty   
27                Paragon  Sponsor      Personal & Beauty   
73                  Nivea  Sponsor      Personal & Beauty   
62  Damn I Love Indonesia  Sponsor     Textiles & Apparel   
40       Head & Shoulders  Sponsor      Personal & Beauty   
71              Bukalapak  Sponsor             E-Commerce   
42               Alfamart  Sponsor  Distribution & Retail   

                                                about  \
56  Mustika Ratu is a well-known Indonesian cosmet...   
60  Holika-holika is a South Korean cosmetics bran...   
80  Wardah is an Indonesian cosmetics and skincare...   
83  The Body Shop is a global beauty and cosmetics...   
27  Paragon Technology and Innovation is an Indone...   
73  Nivea is a global brand that primarily focuses...   
62  Damn I Love Indonesia (DILo) is a lifestyle br...   
40  Head & Shoulders is a well-known brand of anti...   
71  Bukalapak is an Indonesian online marketplace ...   
42  Alfamart is a leading Indonesian convenience s...   

                                             metadata  
56  Sponsor Personal & Beauty Mustika Ratu is a we...  
60  Sponsor Personal & Beauty Holika-holika is a S...  
80  Sponsor Personal & Beauty Wardah is an Indones...  
83  Sponsor Personal & Beauty The Body Shop is a g...  
27  Sponsor Personal & Beauty Paragon Technology a...  
73  Sponsor Personal & Beauty Nivea is a global br...  
62  Sponsor Textiles & Apparel Damn I Love Indones...  
40  Sponsor Personal & Beauty Head & Shoulders is ...  
71  Sponsor E-Commerce Bukalapak is an Indonesian ...  
42  Sponsor Distribution & Retail Alfamart is a le...